import React from "react";
import { createRoot } from "react-dom/client";
import { AuthProvider } from "./context/AuthContext";
import App from "./app/App.tsx";
import "./styles/index.css";
import { registerSW } from "virtual:pwa-register";

// Register the service worker generated by vite-plugin-pwa
const updateSW = registerSW({
  onNeedRefresh() {
    // Prompt user when a new version of the app is available
    if (confirm("🚀 New update available! Click OK to update CounterCraft.")) {
      updateSW(true);
    }
  },
  onOfflineReady() {
    console.log("[PWA] App is ready for offline use ✅");
  },
  onRegistered(registration) {
    console.log("[PWA] Service worker registered:", registration);
  },
  onRegisterError(error) {
    console.error("[PWA] Service worker registration failed:", error);
  },
});

createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <AuthProvider>
      <App />
    </AuthProvider>
  </React.StrictMode>
);